package:
  name: skxray
  version: 0.2.x

source:
  git_url: ../
  git_tag: {{ environ['GIT_FULL_HASH'] }}



build:
  number: 1

requirements:
  build:
    - python
    - distribute
    - numpy
    - six
  run:
    - python
    - numpy
    - scipy
    - six
    - xraylib
    - scikit-image
    - lmfit
    - netcdf4

test:
  requires:
    - nose

about:
  home: http://Nikea.github.io/scikit-xray/
  license: 3-Clause BSD
