package:
  name: scikit-xray
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - numpy
    - six
  run:
    - python
    - numpy
    - scipy
    - six
    - xraylib
    - scikit-image
    - lmfit ==0.8.3
    - netcdf4  # optional, required for skxray.io

test:
  requires:
    - nose
  imports:
    # import all sub-packages and modules
    - skxray
    - skxray.diffraction
    - skxray.fluorescence
    - skxray._version
    - skxray.core
    - skxray.core.utils
    - skxray.core.dpc
    - skxray.core.feature
    - skxray.core.calibration
    - skxray.core.arithmetic
    - skxray.core.recip
    - skxray.core.image
    - skxray.core.cdi
    - skxray.core.roi
    - skxray.core.correlation
    - skxray.core.spectroscopy
    - skxray.core.fitting
    - skxray.core.fitting.xrf_model
    - skxray.core.fitting.background
    - skxray.core.fitting.lineshapes
    - skxray.core.fitting.funcs
    - skxray.core.fitting.models
    - skxray.core.fitting.base
    - skxray.core.fitting.base.parameter_data
    - skxray.core.constants
    - skxray.core.constants.basic
    - skxray.core.constants.xrs
    - skxray.core.constants.xrf
    - skxray.io
    - skxray.io.avizo_io
    - skxray.io.save_powder_output
    - skxray.io.binary
    - skxray.io.net_cdf_io
    - skxray.io.gsas_file_reader

about:
  home: http://scikit-xray.github.io/scikit-xray/
  license: 3-Clause BSD
