package:
  name: nsls2
  version: 0.2.x

source:
  git_url: https://github.com/NSLS-II/NSLS2.git

build:
  number: 1

requirements:
  build:
    - python
    - distribute
    - numpy
    - six
  run:
    - python
    - numpy
    - scipy
    - six
    - xraylib
    - scikit-image
    - lmfit

test:
  requires:
    - nose

about:
  home: http://nsls-ii.github.io/NSLS2/
  license: 3-Clause BSD
