notebooks:

	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/1_time_correlation/*.ipynb
	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/dpc/*.ipynb
	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/reciprocal_space/*.ipynb
	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/speckle/*.ipynb
	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/xrf/*.ipynb
	ipython nbconvert --to rst ../../../scikit-beam-examples/demos/*.ipynb
