name: Documentation

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Versioneer uses the most recent git tag to generate __version__, which appears
        # in the published documentation.
        git fetch --tags

        # These packages are installed in the base environment but may be older
        # versions. Explicitly upgrade them because they often create
        # installation problems if out of date.
        python -m pip install --upgrade pip setuptools numpy

        pip install -r requirements-dev.txt
        pip install -r requirements-docs.txt
        pip install .

        # # python setup.py install build_ext -i
        # python setup.py build_ext -i
        # python setup.py install --single-version-externally-managed --record=record.txt

        pip list
    - name: Build Docs
      run: |
        pushd ../
        git clone https://github.com/scikit-beam/scikit-beam-examples.git
        popd
        pushd docs
        bash build_docs.sh
        popd
    - name: Deploy Documentation
      if: github.repository_owner == 'scikit-beam' && github.ref_name == 'main'
      # We pin to the SHA, not the tag, for security reasons.
      # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847  # v3.9.3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./docs/build/html
        keep_files: true  # Keep old files.
        force_orphan: false  # Keep git history.
